### ISSUE TITLE
not found KudanCV for architecture arm64

### ISSUE THREAD

**Issue by PavelGerashchenko** [kudan-eu/Enhanced-Samples-iOS#1]
Hello, can you help me?
```
ld: framework not found KudanCV for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by eddy-kudan** [comment]
Hi Pavel,
Did you download the iOS framework to drop into the project from our website?

**Comment by PavelGerashchenko** [comment]
Yes, I download the Kudan**AR**.framework from your website and tested it in Xcode 7.2.1 / Xcode 7.3 Beta 4 and in the sample and in the new project, the same error in all cases. Required Kudan**CV**. framework

**Comment by eddy-kudan** [comment]
I'm not able to replicate this issue by doing a fresh clone of this project and using the framework that's on our website.

Could you send a link to your project into the open support ticket that you have with us on feedback@kudan.eu?

**Comment by PavelGerashchenko** [comment]
@eddy-kudan please, answer on my ticket

**Comment by eddy-kudan** [comment]
My colleague has been reviewing your ticket Pavel and attempting to replicate the issue. He will get back via the support channel.

**Comment by gopinathtangutoori** [comment]
The issue is because of the linker flag "-ObjC" which is "other linker flags" settings in build settings. Please give some fix, even am facing the same issue.

**Comment by utiq** [comment]
Hello guys, could you fix that problem?, same issue here

**Comment by adurolms** [comment]
hi guys, any update on this :) i got the same issue (xcode 7.1)

**Comment by nemezis16** [comment]
Same problem, waiting for fixes

**Comment by eddy-kudan** [comment]
The issue with it not working on Xcode 7.3 has been addressed with the latest version of the framework.
