### ISSUE TITLE
App crashing in certain scenario 

### ISSUE THREAD

**Issue by tg9963** [kudan-eu/Enhanced-Samples-iOS#4]
Hi There,

When we use a poor marker like a plain A4 paper or white wall as a marker, then the app crashes. We expect SDK to send back a callback or invoke a delegate method with error parameter if the marker image is not acceptable but it should not cause the app to crash. Here is the stacktrace when it crashes. Kindly suggest how should we tackle this situation.

_ARFab`___lldb_unnamed_function1134$$ARFab:
->  0x100133544 <+0>:  ld1.2d { v2 }, [x1], #16
    0x100133548 <+4>:  ld1.2d { v3 }, [x1], #16
    0x10013354c <+8>:  eor.16b v2, v0, v2
    0x100133550 <+12>: eor.16b v3, v1, v3
    0x100133554 <+16>: cnt.16b v2, v2
    0x100133558 <+20>: cnt.16b v3, v3
    0x10013355c <+24>: uaddlp.8h v2, v2
    0x100133560 <+28>: uaddlp.8h v3, v3
    0x100133564 <+32>: uaddlp.4s v2, v2
    0x100133568 <+36>: uaddlp.4s v3, v3
    0x10013356c <+40>: uaddlp.2d v2, v2
    0x100133570 <+44>: uaddlp.2d v3, v3
    0x100133574 <+48>: addp.2d d2, v2
    0x100133578 <+52>: addp.2d d3, v3
    0x10013357c <+56>: add    d2, d2, d3
    0x100133580 <+60>: fmov   x6, d2
    0x100133584 <+64>: cmp    x6, x4
    0x100133588 <+68>: b.gt   0x100133594               ; ___lldb_unnamed_function1135$$ARFab
    0x10013358c <+72>: mov    x4, x6
    0x100133590 <+76>: mov    x5, x3_

Thanks,

**Comment by eddy-kudan** [comment]
This issue has been dealt with within the support channel.

**Comment by gopinathtangutoori** [comment]
Is this fixed? Even I am facing the same issue.
